# Generated by Django 4.2.13 on 2024-07-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='location',
        ),
    ]
