# Generated by Django 4.1.3 on 2024-07-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_signup_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=100)),
                ('empid', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('password', models.CharField(max_length=32)),
                ('repassword', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
