# Generated by Django 4.1.3 on 2024-07-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_docsignup_alter_signup_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsignup',
            name='address_line_1',
            field=models.CharField(default='Default Address Line 1', max_length=255),
        ),
        migrations.AddField(
            model_name='docsignup',
            name='city',
            field=models.CharField(default='Default City', max_length=100),
        ),
        migrations.AddField(
            model_name='docsignup',
            name='pincode',
            field=models.CharField(default='Default Pincode', max_length=10),
        ),
        migrations.AddField(
            model_name='docsignup',
            name='state',
            field=models.CharField(default='Default State', max_length=100),
        ),
        migrations.AddField(
            model_name='signup',
            name='address_line_1',
            field=models.CharField(default='Default Address Line 1', max_length=255),
        ),
        migrations.AddField(
            model_name='signup',
            name='city',
            field=models.CharField(default='Default City', max_length=100),
        ),
        migrations.AddField(
            model_name='signup',
            name='pincode',
            field=models.CharField(default='Default Pincode', max_length=10),
        ),
        migrations.AddField(
            model_name='signup',
            name='state',
            field=models.CharField(default='Default State', max_length=100),
        ),
    ]
